export const products = [

    {
        id:1,
        lat: 45.531900,
        lng: -73.592300,
        infoWindow: "Beautiful Family House",
        title: "Beautiful Family House",
        mainImg: "/img/properties/property01/img01.jpg",
        address: {
            fullAddress: "5485 Rue Saint-André, Montréal QC,  H2J 4G3",
            streetNumber: 5478,
            streetName: "Rue Saint-André",
            city: "Montreal",
            province: "QC",
            postalCode: " H2J 4G3"},      
        info: {
            type: 'House',
            price: 2200000,
            surface: 450,
            beds: 2,
            baths: 2,
            garage: 2,
            kitchen: 2,
            "AC Rooms": 4,
            "Swimming Pool": "yes",
            "Party Rooms": "yes", 
            balcony: "yes",
            pool: "yes"}           
    },

    {
        id:2,
        lat: 45.505560,
        lng: -73.570670,
        title: "Awesome appartement",
        infoWindow: "Awesome appartement",
        mainImg: "/img/properties/property02/img01.jpg",
        address: {
            fullAddress: "505 Bv de Maisonneuve O, Montréal QC, H3A 3C2",
            streetNumber: 505,
            streetName: "Bv de Maisonneuve O",
            city: "Montreal",
            province: "QC",
            postalCode: "H3A 3C2"},  
        info: {
            type: 'Apartment',
            price: 300000,
            surface: 350,
            beds: 2,
            baths: 1,
            garage: 1,
            kitchen: 1,
            "AC Rooms": 3,
            sauna: "yes",
            jacuzzi: "yes"}           
    },

    {
        id:3,
        lat: 45.507040,
        lng: -73.565870,
        title: "Rooftop Appartment",
        infoWindow: "Rooftop Appartment",
        mainImg: "/img/properties/property03/img01.jpg",
        address: {
            fullAddress: "1100 Rue Jeanne-Mance, Montréal QC, H2Z 1L7",
            streetNumber: 1100,
            streetName: "Rue Jeanne-Mance",
            city: "Montreal",
            province: "QC",
            postalCode: "H2Z 1L7"},
        info: {
            type: 'Apartment',
            price: 640000,
            surface: 550,
            beds: 4,
            baths: 2,
            garage: 2,
            kitchen: 1,   
            spa: "yes",
            balcony: "yes",
            "Fitness Center": "yes"},            
    },

    {
        id:4,
        lat: 45.487640,
        lng: -73.596330,
        title: "Beautiful Condo",
        infoWindow: "Beautiful Condo",
        mainImg: "/img/properties/property04/img01.jpg",
        address: {
            fullAddress: "400 Avenue Clarke, Montréal QC, H3Z 2E7",
            streetNumber: 400,
            streetName: "Avenue Clarke",
            city: "Montreal",
            province: "QC",
            postalCode: "H3Z 2E7"},
        info: {
            type: 'Condo',
            price: 1470000,
            surface: 450,
            beds: 5,
            baths: 3,
            garage: 2,
            kitchen: 2,
            "AC Rooms": 7,
            "Swimming Pool": "yes",
            "Party Rooms": "yes", 
            balcony: "yes",
            pool: "yes"}      
    },

    {
        id:5,
        lat: 45.566965,
        lng: -73.570833,
        title: "Modern Family House",
        infoWindow: "Modern Family House",
        mainImg: "/img/properties/property05/img01.jpg",
        address: {
            fullAddress: "4640 Rue de Bellechasse, Montréal QC, H1T 1Z3",
            streetNumber: 4640,
            streetName: "Rue de Bellechasse",
            city: "Montreal",
            province: "QC",
            postalCode: "H1T 1Z3",
        },
        info: {
            type: 'House',
            price: "2390000",
            surface: 670,
            beds: 2,
            baths: 2,
            garage: 2,
            kitchen: 2,
            spa: "yes",
            balcony: "yes",
            "Fitness Center": "yes",
            pool: "yes"}       
    },

    {
        id:6,
        lat: 45.53820,
        lng: -73.737691,
        title: "Awesome Villa",
        infoWindow: "Awesome Villa",
        mainImg: "/img/properties/property06/img01.jpg",
        address: {
            fullAddress: "2134 Boulevard Gouin Est, Montreal QC, H2B 1X2",
            streetNumber: 2134,
            streetName: "Boulevard Gouin Est",
            city: "Montreal",
            province: "QC",
            postalCode: "H2B 1X2"},
        info : {
            type: 'House',
            price: 125000,
            surface: 950,
            beds: 6,
            baths: 3,
            garage: 3,
            kitchen: 2,
            "Swimming Pool": "yes",
            "Party Rooms": "yes", 
            balcony: "yes"}     
    },

    {
        id:7,
        lat: 45.352298,
        lng: -75.789472,
        title: "Modern residence",
        infoWindow: "Modern residence",
        mainImg: "/img/properties/property07/img01.jpg",
        address: {
            fullAddress: "2725 Queensview Dr, Ottawa ON, K2B 0A1",
            streetNumber: 2725,
            streetName: "Queensview Dr",
            city: "Ottawa",
            province: "ON",
            postalCode: "K2B 0A1"},
        info : {
            type: 'House',
            price: 560000,
            surface: 950,
            beds: 6,
            baths: 3,
            garage: 3,
            kitchen: 2,
            "Swimming Pool": "yes",
            "Party Rooms": "yes", 
            balcony: "yes"}     
    },

    {
        id:8,
        lat: 45.396448,
        lng: -75.607377,
        title: "Awesome Condo",
        infoWindow: "Awesome Condo",
        mainImg: "/img/properties/property08/img01.jpg",
        address: {
            fullAddress: "2730 Lancaster Rd, Ottawa ON, K1B 4S4",
            streetNumber: 2730,
            streetName: "Lancaster Rd",
            city: "Ottawa",
            province: "ON",
            postalCode: "K1B 4S4"},
        info : {
            type: 'Condo',
            price: 1500000,
            surface: 950,
            beds: 6,
            baths: 3,
            garage: 3,
            kitchen: 2,
            "Swimming Pool": "yes",
            "Party Rooms": "yes", 
            balcony: "yes"}     
    },

    {
        id:9,
        lat: 45.387352,
        lng: -75.652116,
        title: "Unique Condo",
        infoWindow: "Unique Condo",
        mainImg: "/img/properties/property09/img01.jpg",
        address: {
            fullAddress: "1640 Kilborn Avenue, Ottawa ON, K1H 8L8",
            streetNumber: 1640,
            streetName: "Kilborn Avenue",
            city: "Ottawa",
            province: "ON",
            postalCode: "K1H 8L8"},
        info : {
            type: 'Condo',
            price: 450000,
            surface: 950,
            beds: 6,
            baths: 3,
            garage: 3,
            kitchen: 2,
            "Swimming Pool": "yes",
            "Party Rooms": "yes", 
            balcony: "yes"}     
    },

    {
        id:10,
        lat: 45.440263,
        lng: -75.653656,
        title: "Stunning Appartment",
        infoWindow: "Stunning appartment",
        mainImg: "/img/properties/property010/img01.jpg",
        address: {
            fullAddress: "391 Montfort Street, Ottawa ON, K1L 8G8",
            streetNumber: 2134,
            streetName: "Boulevard Gouin Est",
            city: "Ottawa",
            province: "ON",
            postalCode: "K1L 8G8"},
        info : {
            type: 'Apartment',
            price: 1150000,
            surface: 950,
            beds: 6,
            baths: 3,
            garage: 3,
            kitchen: 2,
            "Swimming Pool": "yes",
            "Party Rooms": "yes", 
            balcony: "yes"}     
    },

    {
        id:11,
        lat: 45.413616,
        lng: -75.685375,
        title: "Sophisticated Appartment",
        infoWindow: "Sophisticated Appartment",
        mainImg: "/img/properties/property011/img01.jpg",
        address: {
            fullAddress: "45 Argyle Avenue, Ottawa ON, K2P 1B3",
            streetNumber: 45,
            streetName: "Argyle Avenue",
            city: "Ottawa",
            province: "ON",
            postalCode: "K2P 1B3"},
        info : {
            type: 'Apartment',
            price: 2500000,
            surface: 950,
            beds: 6,
            baths: 3,
            garage: 3,
            kitchen: 2,
            "Swimming Pool": "yes",
            "Party Rooms": "yes", 
            balcony: "yes"}    
    },

    {
        id:12,
        lat: 45.411263,
        lng: -75.702088,
        title: "Elegant Apartment",
        infoWindow: "Elegant Apartment",
        mainImg: "/img/properties/property012/img01.jpg",
        address: {
            fullAddress: "600 Gilmour Street, Ottawa ON, K1R 5L8",
            streetNumber: 600,
            streetName: "Gilmour Street",
            city: "Ottawa",
            province: "ON",
            postalCode: "K1R 5L8"},
        info : {
            type: 'Apartment',
            price: 475000,
            surface: 950,
            beds: 6,
            baths: 3,
            garage: 3,
            kitchen: 2,
            "Swimming Pool": "yes",
            "Party Rooms": "yes", 
            balcony: "yes"}     
    },

    {
        id:13,
        lat: 45.417624,
        lng: -75.702577,
        title: "Outstanding Apartment",
        infoWindow: "Outstanding Apartment",
        mainImg: "/img/properties/property013/img01.jpg",
        address: {
            fullAddress: "407 Avenue Laurier Ouest, Ottawa ON, K1R 7Y7",
            streetNumber: 407,
            streetName: "Avenue Laurier Ouest",
            city: "Ottawa",
            province: "ON",
            postalCode: "K1R 7Y7"},
        info : {
            type: 'Apartment',
            price: 3200000,
            surface: 950,
            beds: 6,
            baths: 3,
            garage: 3,
            kitchen: 2,
            "Swimming Pool": "yes",
            "Party Rooms": "yes", 
            balcony: "yes"}     
    },

    {
        id:14,
        lat: 46.807605,
        lng: -71.246658,
        title: "Exceptional Apartment",
        infoWindow: "Exceptional Apartment",
        mainImg: "/img/properties/property014/img01.jpg",
        address: {
            fullAddress: "257 Rue Marie-Louise, Quebec QC, G1N 3H6",
            streetNumber: 257,
            streetName: "Rue Marie-Louise",
            city: "Quebec",
            province: "QC",
            postalCode: "G1N 3H6"},
        info : {
            type: 'Apartment',
            price: 1080000,
            surface: 950,
            beds: 6,
            baths: 3,
            garage: 3,
            kitchen: 2,
            "Swimming Pool": "yes",
            "Party Rooms": "yes", 
            balcony: "yes"}     
    },

    {
        id:15,
        lat: 46.809194,
        lng: -71.221050,
        title: "Modern Condo",
        infoWindow: "Modern Condo",
        mainImg: "/img/properties/property015/img01.jpg",
        address: {
            fullAddress: "495 Rue Saint-Gabriel, Quebec QC, H2B 1X2",
            streetNumber: 495,
            streetName: "Rue Saint-Gabriel",
            city: "Quebec",
            province: "QC",
            postalCode: " H2B 1X2"},
        info : {
            type: 'Condo',
            price: 3500000,
            surface: 950,
            beds: 6,
            baths: 3,
            garage: 3,
            kitchen: 2,
            "Swimming Pool": "yes",
            "Party Rooms": "yes", 
            balcony: "yes"}     
    },

    {
        id:16,
        lat: 46.811609,
        lng: -71.220619,
        title: "Exclusive Condo",
        infoWindow: "Exclusive Condo",
        mainImg: "/img/properties/property016/img01.jpg",
        address: {
            fullAddress: "600 Rue Saint-Olivier, Quebec QC, G1R 1H2",
            streetNumber: 600,
            streetName: "Rue Saint-Olivier",
            city: "Quebec",
            province: "QC",
            postalCode: "G1R 1H2"},
        info : {
            type: 'Condo',
            price: 750000,
            surface: 950,
            beds: 6,
            baths: 3,
            garage: 3,
            kitchen: 2,
            "Swimming Pool": "yes",
            "Party Rooms": "yes", 
            balcony: "yes"}     
    },

    {
        id:17,
        lat: 46.803840,
        lng: -71.312787,
        title: "Sophisticated Residence",
        infoWindow: "Sophisticated Residence",
        mainImg: "/img/properties/property017/img01.jpg",
        address: {
            fullAddress: "3821 Rue Jacques Crépeault, Quebec QC, G1P 2E2",
            streetNumber: 3821,
            streetName: "Rue Jacques Crépeault",
            city: "Quebec",
            province: "QC",
            postalCode: " G1P 2E2"},
        info : {
            type: 'Condo',
            price: 1430000,
            surface: 950,
            beds: 6,
            baths: 3,
            garage: 3,
            kitchen: 2,
            "Swimming Pool": "yes",
            "Party Rooms": "yes", 
            balcony: "yes"}     
    },

    {
        id:18,
        lat: 45.543978,
        lng: -73.626070,
        title: "Awesome Condo",
        infoWindow: "Awesome Condo",
        mainImg: "/img/properties/property018/img01.jpg",
        address: {
            fullAddress: "8300 Rue Saint Gérard, Montreal QC, H2P 2C9",
            streetNumber: 8300 ,
            streetName: "Rue Saint Gérard",
            city: "Montreal",
            province: "QC",
            postalCode: "H2P 2C9"},
        info : {
            type: 'Condo',
            price: 2150000,
            surface: 950,
            beds: 6,
            baths: 3,
            garage: 3,
            kitchen: 2,
            "Swimming Pool": "yes",
            "Party Rooms": "yes", 
            balcony: "yes"}     
    },

    {
        id:19,
        lat: 45.512698,
        lng: -73.607062,
        title: "English Style Residence",
        infoWindow: "English Style Residence",
        mainImg: "/img/properties/property019/img01.jpg",
        address: {
            fullAddress: "8 Avenue Courcelette, Montreal QC, H2V 3A6",
            streetNumber: 8,
            streetName: "Avenue Courcelette",
            city: "Montreal",
            province: "QC",
            postalCode: "H2V 3A6"},
        info : {
            type: 'House',
            price: 3200000,
            surface: 950,
            beds: 6,
            baths: 3,
            garage: 3,
            kitchen: 2,
            "Swimming Pool": "yes",
            "Party Rooms": "yes", 
            balcony: "yes"}     
    },

    {
        id:20,
        lat: 45.488138,
        lng: -73.632168,
        title: "Neoclassical Style",
        infoWindow: "Neoclassical Style",
        mainImg: "/img/properties/property020/img01.jpg",
        address: {
            fullAddress: "4900 Bv Edouard-Montpetit, Montreal QC, H3W 1R1",
            streetNumber: 2134,
            streetName: "Bv Edouard-Montpetit",
            city: "Montreal",
            province: "QC",
            postalCode: "H3W 1R1"},
        info : {
            type: 'House',
            price: 325000,
            surface: 950,
            beds: 6,
            baths: 3,
            garage: 3,
            kitchen: 2,
            "Swimming Pool": "yes",
            "Party Rooms": "yes", 
            balcony: "yes"}     
    },
];